import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    background: {
        flex: 1,
        backgroundColor: '#E1E1E1',
        justifyContent: 'center',
        alignItems: 'center',
    },
    container: {
        backgroundColor: '#F6F7FA',
        borderRadius: 16,
        padding: 24,
        width: '90%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    title: {
        fontSize: 32,
        marginBottom: 6,
        textAlign: 'center',
        color: '#222',
        fontFamily: 'SF-Pro-Medium',
    },
    subtitle: {
        fontSize: 18,
        marginBottom: 32,
        textAlign: 'center',
        color: '#444',
        fontFamily: 'SF-Pro-Medium',
    },
    label: {
        alignSelf: 'flex-start',
        marginBottom: 4,
        marginTop: 12,
        fontSize: 16,
        color: '#333',
        fontFamily: 'SF-Pro-Regular',
    },
    input: {
        width: '100%',
        height: 44,
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 12,
        paddingHorizontal: 12,
        marginBottom: 8,
    },
    passwordContainer: {
        flexDirection: 'row',
        width: '100%',
        height: 44,
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 12,
        paddingHorizontal: 12,
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    passwordInput: {
        flex: 1,
    },
    forgotText: {
        alignSelf: 'flex-end',
        marginTop: 8,
        marginBottom: 20,
        color: '#333',
        fontSize: 14,
        textDecorationLine: 'underline',
        fontFamily: 'SF-Pro-Regular',
    },
    button: {
        backgroundColor: '#0b0f4d',
        borderRadius: 50,
        width: '100%',
        paddingVertical: 12,
        alignItems: 'center',
        marginBottom: 24,
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        fontFamily: 'SF-Pro-Semibold',
    },
    registerText: {
        fontSize: 14,
        textDecorationLine: 'underline',
        color: '#222',
        fontFamily: 'SF-Pro-Regular',
    },
    scrollContainer: {
        flexGrow: 1,
        paddingVertical: 60,
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    inner: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
    },


});